Ais\SemesterBundle\Entity\Semester:
 type: entity
 table: semester
 repositoryClass: Ais\SemesterBundle\Repository\SemesterRepository
 id:
  id: 
   type: integer
   generator: { strategy: AUTO }
 fields:
  semester:
   type: string
   length: 40
  is_active:
   type: boolean
   nullable: true
  is_delete:
   type: boolean
   nullable: true
