# src/Ais/SemesterBundle/Resources/config/validation.yml
Ais\SemesterBundle\Entity\Semester:
    properties:
        semester:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 2
                max: 100
                minMessage: "Your title must be at least {{ limit }} characters length"
                maxMessage: "Your title name cannot be longer than {{ limit }} characters length"
